In [1]:
import os
import pandas as pd
import yaml
import pickle

from utils.training_utils import find_specific_variables

from lightgbm import LGBMClassifier

from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [2]:
features = yaml.safe_load(open(os.path.join('..', 'src', 'config', 'feature_config.yaml'), 'r'))

# Modelo para classificação de um produto em promoção

In [3]:
df = pd.read_csv(os.path.join('..', 'data', 'train_test', 'train_encoded.csv'))

print(df.shape)
df.head()

(32940, 11)

,contact,month,age,cons.conf.idx,cons.price.idx,emp.var.rate,euribor3m,nr.employed,pdays,was_contacted_before,y
0,0.0,9.0,31.0,-29.8,92.379,-3.4,0.803,5017.5,999.0,0.0,0
1,1.0,6.0,39.0,-36.4,93.994,1.1,4.857,5191.0,999.0,0.0,0
2,0.0,3.0,34.0,-42.7,93.918,1.4,4.958,5228.1,999.0,0.0,0
3,1.0,6.0,36.0,-36.4,93.994,1.1,4.856,5191.0,999.0,0.0,0
4,0.0,1.0,25.0,-31.4,92.201,-2.9,0.825,5076.2,999.0,0.0,0

In [4]:
seletor = pickle.load(
    open(os.path.join('..', 'models', 'encoders', 'seletor_2.pkl'), 'rb')
)

df_hyperparams = pickle.load(
    open(os.path.join('..', 'models', 'df_metrics_results_tunning_lgbm.pkl'), 'rb')
)

In [5]:

feature_target = find_specific_variables(features, 'target', specific_value=True)

In [6]:
df_treino, df_valid = train_test_split(df, test_size=0.2, random_state=96)

In [7]:
print(f'Shape Treino: {df_treino.shape}')
print(f'Shape Valid: {df_valid.shape}')

Shape Treino: (26352, 11)
Shape Valid: (6588, 11)

In [8]:
print(f'% Treino: {df_treino[feature_target[0]].mean()}')
print(f'% Valid: {df_valid[feature_target[0]].mean()}')

% Treino: 0.11202185792349727
% Valid: 0.11262902246508803

In [9]:
df_hyperparams[df_hyperparams.value == max(df_hyperparams.value)].T

                                                  36
number                                            36
value                                       0.803423
datetime_start            2025-04-02 02:00:26.918889
datetime_complete         2025-04-02 02:00:27.690854
duration                      0 days 00:00:00.771965
params_class_weight                         balanced
params_learning_rate                        0.012926
params_max_depth                                   6
params_min_child_samples                          29
params_n_estimators                              346
params_num_leaves                                 15
state                                       COMPLETE

In [10]:
best_row = df_hyperparams.loc[df_hyperparams['value'].idxmax()]
best_params = best_row.filter(like='params_')
hyper_params = {col.replace('params_', ''): best_params[col] for col in best_params.index}


hyper_params.update({
    'eval_metric': 'auc',
})

In [11]:
hyper_params

{'class_weight': 'balanced',
 'learning_rate': 0.01292595418150018,
 'max_depth': 6,
 'min_child_samples': 29,
 'n_estimators': 346,
 'num_leaves': 15,
 'eval_metric': 'auc'}

In [12]:
model = LGBMClassifier(
    **hyper_params,
    random_state=12,
    n_jobs=-1
)

model

LGBMClassifier(class_weight='balanced', eval_metric='auc',
               learning_rate=0.01292595418150018, max_depth=6,
               min_child_samples=29, n_estimators=346, num_leaves=15,
               random_state=12)

In [13]:
model.fit(
    df_treino[seletor.features].values,
    df_treino[feature_target].values,
    eval_set=[(df_valid[seletor.features].values, df_valid[feature_target].values)],
    verbose=True
)

[LightGBM] [Warning] Unknown parameter: eval_metric
[1]	valid_0's binary_logloss: 0.689365
[2]	valid_0's binary_logloss: 0.685666
[3]	valid_0's binary_logloss: 0.682055
[4]	valid_0's binary_logloss: 0.678526
[5]	valid_0's binary_logloss: 0.675072
[6]	valid_0's binary_logloss: 0.6717
[7]	valid_0's binary_logloss: 0.668394
[8]	valid_0's binary_logloss: 0.665167
[9]	valid_0's binary_logloss: 0.662023
[10]	valid_0's binary_logloss: 0.658932
[11]	valid_0's binary_logloss: 0.655916
[12]	valid_0's binary_logloss: 0.652975
[13]	valid_0's binary_logloss: 0.650087
[14]	valid_0's binary_logloss: 0.647268
[15]	valid_0's binary_logloss: 0.644486
[16]	valid_0's binary_logloss: 0.641757
[17]	valid_0's binary_logloss: 0.639129
[18]	valid_0's binary_logloss: 0.636559
[19]	valid_0's binary_logloss: 0.634033
[20]	valid_0's binary_logloss: 0.631569
[21]	valid_0's binary_logloss: 0.629161
[22]	valid_0's binary_logloss: 0.626791
[23]	valid_0's binary_logloss: 0.624479
[24]	valid_0's binary_logloss: 0.622213
[25]	valid_0's binary_logloss: 0.619998
[26]	valid_0's binary_logloss: 0.617825
[27]	valid_0's binary_logloss: 0.615705
[28]	valid_0's binary_logloss: 0.613623
[29]	valid_0's binary_logloss: 0.611577
[30]	valid_0's binary_logloss: 0.60958
[31]	valid_0's binary_logloss: 0.607625
[32]	valid_0's binary_logloss: 0.605714
[33]	valid_0's binary_logloss: 0.603851
[34]	valid_0's binary_logloss: 0.60202
[35]	valid_0's binary_logloss: 0.600225
[36]	valid_0's binary_logloss: 0.59846
[37]	valid_0's binary_logloss: 0.596755
[38]	valid_0's binary_logloss: 0.595068
[39]	valid_0's binary_logloss: 0.593411
[40]	valid_0's binary_logloss: 0.5918
[41]	valid_0's binary_logloss: 0.590215
[42]	valid_0's binary_logloss: 0.588652
[43]	valid_0's binary_logloss: 0.58713
[44]	valid_0's binary_logloss: 0.585646
[45]	valid_0's binary_logloss: 0.584203
[46]	valid_0's binary_logloss: 0.582762
[47]	valid_0's binary_logloss: 0.581363
[48]	valid_0's binary_logloss: 0.579977
[49]	valid_0's binary_logloss: 0.578638
[50]	valid_0's binary_logloss: 0.577336
[51]	valid_0's binary_logloss: 0.576035
[52]	valid_0's binary_logloss: 0.574778
[53]	valid_0's binary_logloss: 0.573523
[54]	valid_0's binary_logloss: 0.572293
[55]	valid_0's binary_logloss: 0.57108
[56]	valid_0's binary_logloss: 0.569908
[57]	valid_0's binary_logloss: 0.568741
[58]	valid_0's binary_logloss: 0.567591
[59]	valid_0's binary_logloss: 0.566472
[60]	valid_0's binary_logloss: 0.56539
[61]	valid_0's binary_logloss: 0.564332
[62]	valid_0's binary_logloss: 0.563282
[63]	valid_0's binary_logloss: 0.56225
[64]	valid_0's binary_logloss: 0.561238
[65]	valid_0's binary_logloss: 0.560264
[66]	valid_0's binary_logloss: 0.559294
[67]	valid_0's binary_logloss: 0.558348
[68]	valid_0's binary_logloss: 0.557419
[69]	valid_0's binary_logloss: 0.556503
[70]	valid_0's binary_logloss: 0.555598
[71]	valid_0's binary_logloss: 0.554724
[72]	valid_0's binary_logloss: 0.553892
[73]	valid_0's binary_logloss: 0.553054
[74]	valid_0's binary_logloss: 0.552228
[75]	valid_0's binary_logloss: 0.551414
[76]	valid_0's binary_logloss: 0.550618
[77]	valid_0's binary_logloss: 0.549819
[78]	valid_0's binary_logloss: 0.549058
[79]	valid_0's binary_logloss: 0.548329
[80]	valid_0's binary_logloss: 0.547583
[81]	valid_0's binary_logloss: 0.546884
[82]	valid_0's binary_logloss: 0.546158
[83]	valid_0's binary_logloss: 0.545461
[84]	valid_0's binary_logloss: 0.544789
[85]	valid_0's binary_logloss: 0.544128
[86]	valid_0's binary_logloss: 0.543475
[87]	valid_0's binary_logloss: 0.542822
[88]	valid_0's binary_logloss: 0.542196
[89]	valid_0's binary_logloss: 0.54159
[90]	valid_0's binary_logloss: 0.540994
[91]	valid_0's binary_logloss: 0.540418
[92]	valid_0's binary_logloss: 0.539836
[93]	valid_0's binary_logloss: 0.539274
[94]	valid_0's binary_logloss: 0.538716
[95]	valid_0's binary_logloss: 0.538169
[96]	valid_0's binary_logloss: 0.537645
[97]	valid_0's binary_logloss: 0.537114
[98]	valid_0's binary_logloss: 0.536594
[99]	valid_0's binary_logloss: 0.536076
[100]	valid_0's binary_logloss: 0.535567
[101]	valid_0's binary_logloss: 0.535096
[102]	valid_0's binary_logloss: 0.534607
[103]	valid_0's binary_logloss: 0.534154
[104]	valid_0's binary_logloss: 0.533684
[105]	valid_0's binary_logloss: 0.533251
[106]	valid_0's binary_logloss: 0.532793
[107]	valid_0's binary_logloss: 0.532365
[108]	valid_0's binary_logloss: 0.531934
[109]	valid_0's binary_logloss: 0.531506
[110]	valid_0's binary_logloss: 0.531093
[111]	valid_0's binary_logloss: 0.530698
[112]	valid_0's binary_logloss: 0.530285
[113]	valid_0's binary_logloss: 0.529897
[114]	valid_0's binary_logloss: 0.52951
[115]	valid_0's binary_logloss: 0.529122
[116]	valid_0's binary_logloss: 0.528749
[117]	valid_0's binary_logloss: 0.5284
[118]	valid_0's binary_logloss: 0.52805
[119]	valid_0's binary_logloss: 0.527689
[120]	valid_0's binary_logloss: 0.527339
[121]	valid_0's binary_logloss: 0.527001
[122]	valid_0's binary_logloss: 0.526653
[123]	valid_0's binary_logloss: 0.526341
[124]	valid_0's binary_logloss: 0.526022
[125]	valid_0's binary_logloss: 0.525688
[126]	valid_0's binary_logloss: 0.5254
[127]	valid_0's binary_logloss: 0.525103
[128]	valid_0's binary_logloss: 0.524787
[129]	valid_0's binary_logloss: 0.524521
[130]	valid_0's binary_logloss: 0.524209
[131]	valid_0's binary_logloss: 0.52393
[132]	valid_0's binary_logloss: 0.52366
[133]	valid_0's binary_logloss: 0.523411
[134]	valid_0's binary_logloss: 0.523128
[135]	valid_0's binary_logloss: 0.522865
[136]	valid_0's binary_logloss: 0.522619
[137]	valid_0's binary_logloss: 0.522374
[138]	valid_0's binary_logloss: 0.522118
[139]	valid_0's binary_logloss: 0.521882
[140]	valid_0's binary_logloss: 0.521638
[141]	valid_0's binary_logloss: 0.521397
[142]	valid_0's binary_logloss: 0.521183
[143]	valid_0's binary_logloss: 0.520945
[144]	valid_0's binary_logloss: 0.520719
[145]	valid_0's binary_logloss: 0.52049
[146]	valid_0's binary_logloss: 0.520266
[147]	valid_0's binary_logloss: 0.520068
[148]	valid_0's binary_logloss: 0.519874
[149]	valid_0's binary_logloss: 0.519694
[150]	valid_0's binary_logloss: 0.519514
[151]	valid_0's binary_logloss: 0.519333
[152]	valid_0's binary_logloss: 0.519162
[153]	valid_0's binary_logloss: 0.51898
[154]	valid_0's binary_logloss: 0.51881
[155]	valid_0's binary_logloss: 0.518643
[156]	valid_0's binary_logloss: 0.51848
[157]	valid_0's binary_logloss: 0.518304
[158]	valid_0's binary_logloss: 0.518143
[159]	valid_0's binary_logloss: 0.517972
[160]	valid_0's binary_logloss: 0.517805
[161]	valid_0's binary_logloss: 0.517635
[162]	valid_0's binary_logloss: 0.517471
[163]	valid_0's binary_logloss: 0.517302
[164]	valid_0's binary_logloss: 0.517146
[165]	valid_0's binary_logloss: 0.516978
[166]	valid_0's binary_logloss: 0.516823
[167]	valid_0's binary_logloss: 0.516672
[168]	valid_0's binary_logloss: 0.516512
[169]	valid_0's binary_logloss: 0.516374
[170]	valid_0's binary_logloss: 0.516226
[171]	valid_0's binary_logloss: 0.516078
[172]	valid_0's binary_logloss: 0.515949
[173]	valid_0's binary_logloss: 0.515805
[174]	valid_0's binary_logloss: 0.515675
[175]	valid_0's binary_logloss: 0.515539
[176]	valid_0's binary_logloss: 0.515412
[177]	valid_0's binary_logloss: 0.515282
[178]	valid_0's binary_logloss: 0.515159
[179]	valid_0's binary_logloss: 0.515044
[180]	valid_0's binary_logloss: 0.514922
[181]	valid_0's binary_logloss: 0.514815
[182]	valid_0's binary_logloss: 0.514693
[183]	valid_0's binary_logloss: 0.514579
[184]	valid_0's binary_logloss: 0.514468
[185]	valid_0's binary_logloss: 0.514368
[186]	valid_0's binary_logloss: 0.514266
[187]	valid_0's binary_logloss: 0.514168
[188]	valid_0's binary_logloss: 0.514067
[189]	valid_0's binary_logloss: 0.513978
[190]	valid_0's binary_logloss: 0.513895
[191]	valid_0's binary_logloss: 0.513803
[192]	valid_0's binary_logloss: 0.51372
[193]	valid_0's binary_logloss: 0.51362
[194]	valid_0's binary_logloss: 0.513532
[195]	valid_0's binary_logloss: 0.513413
[196]	valid_0's binary_logloss: 0.513333
[197]	valid_0's binary_logloss: 0.513258
[198]	valid_0's binary_logloss: 0.513193
[199]	valid_0's binary_logloss: 0.513081
[200]	valid_0's binary_logloss: 0.512974
[201]	valid_0's binary_logloss: 0.512905
[202]	valid_0's binary_logloss: 0.512783
[203]	valid_0's binary_logloss: 0.51268
[204]	valid_0's binary_logloss: 0.51261
[205]	valid_0's binary_logloss: 0.512513
[206]	valid_0's binary_logloss: 0.512405
[207]	valid_0's binary_logloss: 0.512339
[208]	valid_0's binary_logloss: 0.512236
[209]	valid_0's binary_logloss: 0.512146
[210]	valid_0's binary_logloss: 0.51208
[211]	valid_0's binary_logloss: 0.511978
[212]	valid_0's binary_logloss: 0.511893
[213]	valid_0's binary_logloss: 0.511828
[214]	valid_0's binary_logloss: 0.511741
[215]	valid_0's binary_logloss: 0.511669
[216]	valid_0's binary_logloss: 0.511604
[217]	valid_0's binary_logloss: 0.511523
[218]	valid_0's binary_logloss: 0.511449
[219]	valid_0's binary_logloss: 0.511391
[220]	valid_0's binary_logloss: 0.511316
[221]	valid_0's binary_logloss: 0.511237
[222]	valid_0's binary_logloss: 0.511176
[223]	valid_0's binary_logloss: 0.511111
[224]	valid_0's binary_logloss: 0.511047
[225]	valid_0's binary_logloss: 0.510991
[226]	valid_0's binary_logloss: 0.510922
[227]	valid_0's binary_logloss: 0.510863
[228]	valid_0's binary_logloss: 0.510808
[229]	valid_0's binary_logloss: 0.510734
[230]	valid_0's binary_logloss: 0.510671
[231]	valid_0's binary_logloss: 0.510623
[232]	valid_0's binary_logloss: 0.510555
[233]	valid_0's binary_logloss: 0.510488
[234]	valid_0's binary_logloss: 0.510436
[235]	valid_0's binary_logloss: 0.510388
[236]	valid_0's binary_logloss: 0.510325
[237]	valid_0's binary_logloss: 0.510263
[238]	valid_0's binary_logloss: 0.510214
[239]	valid_0's binary_logloss: 0.510166
[240]	valid_0's binary_logloss: 0.51012
[241]	valid_0's binary_logloss: 0.510075
[242]	valid_0's binary_logloss: 0.510031
[243]	valid_0's binary_logloss: 0.50999
[244]	valid_0's binary_logloss: 0.50995
[245]	valid_0's binary_logloss: 0.509907
[246]	valid_0's binary_logloss: 0.509857
[247]	valid_0's binary_logloss: 0.50982
[248]	valid_0's binary_logloss: 0.509783
[249]	valid_0's binary_logloss: 0.509735
[250]	valid_0's binary_logloss: 0.509699
[251]	valid_0's binary_logloss: 0.509667
[252]	valid_0's binary_logloss: 0.50963
[253]	valid_0's binary_logloss: 0.509599
[254]	valid_0's binary_logloss: 0.509567
[255]	valid_0's binary_logloss: 0.509526
[256]	valid_0's binary_logloss: 0.509468
[257]	valid_0's binary_logloss: 0.50944
[258]	valid_0's binary_logloss: 0.50941
[259]	valid_0's binary_logloss: 0.509382
[260]	valid_0's binary_logloss: 0.509353
[261]	valid_0's binary_logloss: 0.509327
[262]	valid_0's binary_logloss: 0.509312
[263]	valid_0's binary_logloss: 0.509285
[264]	valid_0's binary_logloss: 0.509261
[265]	valid_0's binary_logloss: 0.509222
[266]	valid_0's binary_logloss: 0.509209
[267]	valid_0's binary_logloss: 0.509182
[268]	valid_0's binary_logloss: 0.509158
[269]	valid_0's binary_logloss: 0.509124
[270]	valid_0's binary_logloss: 0.509091
[271]	valid_0's binary_logloss: 0.509058
[272]	valid_0's binary_logloss: 0.509039
[273]	valid_0's binary_logloss: 0.509007
[274]	valid_0's binary_logloss: 0.50899
[275]	valid_0's binary_logloss: 0.508952
[276]	valid_0's binary_logloss: 0.508916
[277]	valid_0's binary_logloss: 0.508881
[278]	valid_0's binary_logloss: 0.508848
[279]	valid_0's binary_logloss: 0.508828
[280]	valid_0's binary_logloss: 0.508796
[281]	valid_0's binary_logloss: 0.508768
[282]	valid_0's binary_logloss: 0.508739
[283]	valid_0's binary_logloss: 0.508711
[284]	valid_0's binary_logloss: 0.508693
[285]	valid_0's binary_logloss: 0.508667
[286]	valid_0's binary_logloss: 0.508642
[287]	valid_0's binary_logloss: 0.508607
[288]	valid_0's binary_logloss: 0.508588
[289]	valid_0's binary_logloss: 0.508554
[290]	valid_0's binary_logloss: 0.508532
[291]	valid_0's binary_logloss: 0.508506
[292]	valid_0's binary_logloss: 0.508487
[293]	valid_0's binary_logloss: 0.50846
[294]	valid_0's binary_logloss: 0.508431
[295]	valid_0's binary_logloss: 0.50841
[296]	valid_0's binary_logloss: 0.508386
[297]	valid_0's binary_logloss: 0.508354
[298]	valid_0's binary_logloss: 0.508332
[299]	valid_0's binary_logloss: 0.508315
[300]	valid_0's binary_logloss: 0.508299
[301]	valid_0's binary_logloss: 0.508283
[302]	valid_0's binary_logloss: 0.508267
[303]	valid_0's binary_logloss: 0.508248
[304]	valid_0's binary_logloss: 0.508227
[305]	valid_0's binary_logloss: 0.508208
[306]	valid_0's binary_logloss: 0.508195
[307]	valid_0's binary_logloss: 0.508179
[308]	valid_0's binary_logloss: 0.508156
[309]	valid_0's binary_logloss: 0.508143
[310]	valid_0's binary_logloss: 0.508124
[311]	valid_0's binary_logloss: 0.508113
[312]	valid_0's binary_logloss: 0.508098
[313]	valid_0's binary_logloss: 0.508088
[314]	valid_0's binary_logloss: 0.508074
[315]	valid_0's binary_logloss: 0.508052
[316]	valid_0's binary_logloss: 0.508038
[317]	valid_0's binary_logloss: 0.508027
[318]	valid_0's binary_logloss: 0.508018
[319]	valid_0's binary_logloss: 0.507999
[320]	valid_0's binary_logloss: 0.507982
[321]	valid_0's binary_logloss: 0.507966
[322]	valid_0's binary_logloss: 0.507945
[323]	valid_0's binary_logloss: 0.507936
[324]	valid_0's binary_logloss: 0.507922
[325]	valid_0's binary_logloss: 0.507911
[326]	valid_0's binary_logloss: 0.507902
[327]	valid_0's binary_logloss: 0.507884
[328]	valid_0's binary_logloss: 0.507874
[329]	valid_0's binary_logloss: 0.507872
[330]	valid_0's binary_logloss: 0.507864
[331]	valid_0's binary_logloss: 0.507852
[332]	valid_0's binary_logloss: 0.507843
[333]	valid_0's binary_logloss: 0.507833
[334]	valid_0's binary_logloss: 0.507828
[335]	valid_0's binary_logloss: 0.507818
[336]	valid_0's binary_logloss: 0.507809
[337]	valid_0's binary_logloss: 0.507797
[338]	valid_0's binary_logloss: 0.507751
[339]	valid_0's binary_logloss: 0.507749
[340]	valid_0's binary_logloss: 0.507734
[341]	valid_0's binary_logloss: 0.507699
[342]	valid_0's binary_logloss: 0.507688
[343]	valid_0's binary_logloss: 0.507675
[344]	valid_0's binary_logloss: 0.50764
[345]	valid_0's binary_logloss: 0.507633
[346]	valid_0's binary_logloss: 0.507628

LGBMClassifier(class_weight='balanced', eval_metric='auc',
               learning_rate=0.01292595418150018, max_depth=6,
               min_child_samples=29, n_estimators=346, num_leaves=15,
               random_state=12)

In [14]:
pickle.dump(
    model, 
    open(os.path.join('..', 'models', 'predictors', 'model.pkl'), 'wb')
)